//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brewery.Core.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BreweryDictionary {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BreweryDictionary() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Brewery.Core.Resources.BreweryDictionary", typeof(BreweryDictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string SplashViewModel_Title_Text {
            get {
                return ResourceManager.GetString("SplashViewModel_Title_Text", resourceCulture);
            }
        }
        
        internal static string Request_NoInternetConnection {
            get {
                return ResourceManager.GetString("Request_NoInternetConnection", resourceCulture);
            }
        }
        
        internal static string Request_NoEndpointConnection {
            get {
                return ResourceManager.GetString("Request_NoEndpointConnection", resourceCulture);
            }
        }
        
        internal static string SplashViewModel_ErrorLoadingDataDialog_TitleText {
            get {
                return ResourceManager.GetString("SplashViewModel_ErrorLoadingDataDialog_TitleText", resourceCulture);
            }
        }
        
        internal static string SplashViewModel_Error_LoadingDataDialog_ButtonText {
            get {
                return ResourceManager.GetString("SplashViewModel_Error_LoadingDataDialog_ButtonText", resourceCulture);
            }
        }
        
        internal static string HomeViewModel_Title_text {
            get {
                return ResourceManager.GetString("HomeViewModel_Title_text", resourceCulture);
            }
        }
        
        internal static string BreweryDetailViewModel_Brewery_Name_Text {
            get {
                return ResourceManager.GetString("BreweryDetailViewModel_Brewery_Name_Text", resourceCulture);
            }
        }
        
        internal static string BreweryDetailViewModel_Brewery_Type_Text {
            get {
                return ResourceManager.GetString("BreweryDetailViewModel_Brewery_Type_Text", resourceCulture);
            }
        }
        
        internal static string BreweryDetailViewModel_Brewery_Address_Text {
            get {
                return ResourceManager.GetString("BreweryDetailViewModel_Brewery_Address_Text", resourceCulture);
            }
        }
        
        internal static string BreweryDetailViewModel_Brewery_City_Text {
            get {
                return ResourceManager.GetString("BreweryDetailViewModel_Brewery_City_Text", resourceCulture);
            }
        }
        
        internal static string BreweryDetailViewModel_Brewery_State_Text {
            get {
                return ResourceManager.GetString("BreweryDetailViewModel_Brewery_State_Text", resourceCulture);
            }
        }
        
        internal static string BreweryDetailViewModel_Brewery_PostalCode_Text {
            get {
                return ResourceManager.GetString("BreweryDetailViewModel_Brewery_PostalCode_Text", resourceCulture);
            }
        }
        
        internal static string BreweryDetailViewModel_Brewery_Longitude_Text {
            get {
                return ResourceManager.GetString("BreweryDetailViewModel_Brewery_Longitude_Text", resourceCulture);
            }
        }
        
        internal static string BreweryDetailViewModel_Brewery_Latitude_Text {
            get {
                return ResourceManager.GetString("BreweryDetailViewModel_Brewery_Latitude_Text", resourceCulture);
            }
        }
        
        internal static string BreweryDetailViewModel_Brewery_Phone_Text {
            get {
                return ResourceManager.GetString("BreweryDetailViewModel_Brewery_Phone_Text", resourceCulture);
            }
        }
        
        internal static string BreweryDetailViewModel_Brewery_Website_Text {
            get {
                return ResourceManager.GetString("BreweryDetailViewModel_Brewery_Website_Text", resourceCulture);
            }
        }
        
        internal static string BreweryDetailViewModel_Brewery_StateProvince_Text {
            get {
                return ResourceManager.GetString("BreweryDetailViewModel_Brewery_StateProvince_Text", resourceCulture);
            }
        }
        
        internal static string BreweryDetailViewModel_Brewery_Street_Text {
            get {
                return ResourceManager.GetString("BreweryDetailViewModel_Brewery_Street_Text", resourceCulture);
            }
        }
    }
}
